<template>
  <Layout :title="$page.project.title">
    <article class="project-post">
      <div class="project-flexbox">
        <div class="left">
          <g-image
            class="thumbnail"
            :src="$page.project.thumbnail"
            :alt="$page.project.title"
          />
        </div>
        <div class="right">
          <ProjectMeta
            :title="$page.project.title"
            :categories="$page.project.categories"
            :year="$page.project.year"
          />
        </div>
      </div>
      <div class="content" v-html="$page.project.content" />
    </article>
  </Layout>
</template>

<page-query>
query Project ($path: String!) {
  project: project(path: $path) {
    title
    thumbnail
    year
    categories
    content
  }
}
</page-query>

<script>
import ProjectMeta from "@/components/ProjectMeta";

export default {
  components: {
    ProjectMeta,
  },
  mounted() {
    // Instead of checking for firstChild nodes that is text elements,
    // check and see if the p tags only contains img elements and that noscript
    // generated by Gridsome.
    const contentElements = document.querySelectorAll("p");
    contentElements.forEach(
      (element) =>
        element.firstChild.nodeName === "#text" &&
        element.classList.add("content-text")
    );
  },
};
</script>

<style lang="scss">
.project-post {
  padding: 0 2rem;
  margin-bottom: 8rem;
}

.project-flexbox {
  display: flex;
  @media (max-width: 599px) {
    flex-direction: column;
  }
}

.left, .right {
  width: 50%;
  @media (max-width: 599px) {
    width: 100%;
  }
}

.right {
  padding: 50px; 
   @media (max-width: 599px) {
     padding: 10px;
  }
}

.thumbnail {
  width:100%;
}

img {
  // width: 100% !important;
  margin-bottom: 2rem;
}

p {
  margin: 0;
}

.content-text {
  padding: 4rem 0 6rem 0;
  font-size: 2rem;
  font-weight: 400;
  margin-left: 0;
  max-width: 780px;
  line-height: 1.5;
  @media (min-width: 920px) {
    margin-left: 40%;
  }
}

.imagesContainer {
  display: flex;
  flex-wrap: wrap;
}

.image {
  padding: 25px;
  width: 50%;
  @media (max-width: 599px) {
    width: 100%;
    padding: 0;
    // padding: 10px;
  }
}


</style>
